from enum import Enum


class Assumption(Enum):
    ALGEBRAIC = "algebraic"
    COMMUTATIVE = "commutative"
    COMPLEX = "complex"
    EXTENDED_NEGATIVE = "extended_negative"
    EXTENDED_NONNEGATIVE = "extended_nonnegative"
    EXTENDED_NONPOSITIVE = "extended_nonpositive"
    EXTENDED_NONZERO = "extended_nonzero"
    EXTENDED_POSITIVE = "extended_positive"
    EXTENDED_REAL = "extended_real"
    FINITE = "finite"
    HERMITIAN = "hermitian"
    IMAGINARY = "imaginary"
    INFINITE = "infinite"
    INTEGER = "integer"
    IRATIONAL = "irrational"
    NEGATIVE = "negative"
    NONINTEGER = "noninteger"
    NONNEGATIVE = "nonnegative"
    NONPOSITIVE = "nonpositive"
    NONZERO = "nonzero"
    POSITIVE = "positive"
    RATIONAL = "rational"
    REAL = "real"
    TRANSCENDENTAL = "transcendental"
    ZERO = "zero"
